name: Check for rebuild

on:
  workflow_call:
    inputs:
      version:
        description: 'A php version that should be using to build the image'
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      out-of-date: ${{ steps.check.outputs.out-of-date }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Check if update on base image is available
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@v1
        with:
          parent-image: php:${{ inputs.version }}-fpm
          my-image: ${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:${{ inputs.version }}

  build:
    name: Production Build and Push
    if: needs.check.outputs.out-of-date == 'true'
    needs: check
    uses: ./.github/workflows/partials/production-build-and-push.yml
    with:
      version: ${{ inputs.version }}
