name: Production Build
description: Bulid and Push the image
inputs:
  github_token:
    required: true
    description: 'token for github packages'
  repository:
    required: true
    description: 'Repository URL'
  image_name:
    required: true
    description: 'Image name'
  version:
    required: true
    description: 'A php version that should be using to build the image'
  context:
    required: true
    description: 'Path to folder'
    default: .
  tag-suffix:
    required: false
    description: 'Suffix for sub versions of an image'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.repository }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and Push
      if: ${{ !inputs.tag-suffix }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: true
        build-args: |
          PHP_VERSION=${{ inputs.version }}
        tags: ${{ inputs.repository }}/${{ inputs.image_name }}:${{ inputs.version }}
        cache-from: type=gha,scope=${{ github.ref_name }}-${{ inputs.version }}
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ inputs.version }}

    - name: Build and Push
      if: ${{ inputs.tag-suffix }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: true
        build-args: |
          PHP_VERSION=${{ inputs.version }}
        tags: ${{ inputs.repository }}/${{ inputs.image_name }}-${{ inputs.tag-suffix }}:${{ inputs.version }}
        cache-from: type=gha,scope=${{ github.ref_name }}-${{ inputs.tag-suffix }}-${{ inputs.version }}
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ inputs.tag-suffix }}-${{ inputs.version }}
