name: Production Build
description: Bulid and Push the image
inputs:
  github_token:
    required: true
    description: 'token for github packages'
  repository:
    required: true
    description: 'Repository URL'
  image-name:
    required: true
    description: 'Image name'
  image-version:
    required: true
    description: 'A php version that should be using to build the image'
  context:
    required: true
    description: 'Path to folder'
    default: .

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.repository }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: true
        build-args: |
          PHP_VERSION=${{ inputs.image-version }}
        tags: ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.image-version }}
        cache-from: type=gha,scope=${{ inputs.image-name }}-${{ github.ref_name }}-${{ inputs.image-version }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}-${{ github.ref_name }}-${{ inputs.image-version }}
