name: CI

on: [push, workflow_dispatch]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile"
          ignore: DL3008,DL3022
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "**/Dockerfile"
          recursive: true
          ignore: DL3008,DL3022

