name: "cron: Check for rebuild"

on:
  schedule:
    - cron: '0 4 * * MON'
  workflow_dispatch:

jobs:
  build:
    name: Check for rebuild
    strategy:
      matrix:
        version: [ '8.0', '8.1', '8.2', '8.3' ]
    uses: ./.github/workflows/check-for-rebuild.yml
    with:
      version: ${{ matrix.version }}
