name: "cron: Check for rebuild"

on:
  schedule:
    - cron: '0 4 * * MON'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php-versions-matrix
        id: setup-matrix

  build:
    name: Check for rebuild
    needs: setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    uses: ./.github/workflows/check-for-rebuild.yml
    with:
      version: ${{ matrix.version }}
      is-latest: ${{ matrix.is-latest }}
