name: Lint
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dockerfile-lint
        with:
          dockerfile: "Dockerfile"
      - uses: ./.github/actions/dockerfile-lint
        with:
          dockerfile: "**/Dockerfile"


