name: Production Build and Push

on:
  workflow_call:
    inputs:
      version:
        description: 'A php version that should be using to build the image'
        required: true
        type: string

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/production-build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          context: .

  build-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        context: [ { tag: 'dev', path: './development' }, { tag: 'prod', path: './production' } ]
    needs: build-php-base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/production-build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          context: ${{ matrix.context.path }}
          tag-suffix: ${{ matrix.context.tag }}
