name: Production Build and Push

on:
  workflow_call:
    inputs:
      version:
        description: 'A php version that should be using to build the image'
        required: true
        type: string

env:
  REPOSITORY: ghcr.io
  IMAGE_NAME: clicksports/php-fpm

jobs:
  build-php-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/production-build
        with:
          version: ${{ inputs.version }}

  build-push-php:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        context: [ { tag: 'dev', path: './development' }, { tag: 'prod', path: './production' } ]
    needs: build-php-base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/production-build
        with:
          version: ${{ inputs.version }}
          context: ${{ matrix.context }}
