name: Production Build and Push

on:
  workflow_call:
    inputs:
      version:
        description: 'A php version that should be using to build the image'
        required: true
        type: string
      is-latest:
        description: 'Whether this is the latest PHP version'
        required: false
        type: boolean
        default: false

jobs:
  # Build base image for both architectures in parallel
  build-base:
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    permissions:
      contents: read
      packages: write
    strategy:
      max-parallel: 2
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/production-build-single-arch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ vars.REPOSITORY }}
          image-variant: base
          image-version: ${{ inputs.version }}
          arch: ${{ matrix.arch }}

  # Build dev and prod images for both architectures in parallel (4 combinations)
  build-env:
    needs: build-base
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    permissions:
      contents: read
      packages: write
    strategy:
      max-parallel: 4
      matrix:
        env: [dev, prod]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/production-build-single-arch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ vars.REPOSITORY }}
          image-variant: ${{ matrix.env }}
          image-version: ${{ inputs.version }}
          arch: ${{ matrix.arch }}

  # Merge dev and prod multi-arch manifests in parallel
  merge-env:
    needs: build-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      max-parallel: 2
      matrix:
        env: [dev, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/production-build-merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ vars.REPOSITORY }}
          image-variant: ${{ matrix.env }}
          image-version: ${{ inputs.version }}
          is-latest: ${{ inputs.is-latest }}
