name: Release Update

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
  build:
    name: Production Build and Push
    uses: ./.github/workflows/production-build-and-push.yml