name: Release Update

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php-versions-matrix
        id: setup-matrix

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml

  build:
    name: Production Build and Push
    needs: setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    uses: ./.github/workflows/production-build-and-push.yml
    with:
      version: ${{ matrix.version }}
      is-latest: ${{ matrix.is-latest }}